language: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

secure: "DMcUCczD2QDotaicyQKfh0si7BYR/qtPVM+vIXVhUS5l2AI7vaZBiD6GAdhdlb1gHgPAM3m2lHI+1oiwMBt09bfSZ6hXmibubWPL+ITKTir8uTGbIDqGwkJX0wQT2ggymcd3tZlahdOne2LSAxIXXVtamdoWuMQJHS2KUr4jAZYNbF12NsrDvsxfqoOb9FKOAU/dYsoCERT+HQv8W2/M5a6Rp02YxIZhVOaaVwuMmR2YExsnJ5zanXrUzvBuQ9RT8tNPDnSPSi73EBH1eNqyImllaWZMrKs64UiRqJJDksikS8d+WGwhCB8rzzJH6mTrPCuV8CNv/20WghzOLRbNKIudLGm/utDCKfxaRM5ysfaPQlMt4huo8d36ufsHVY1KSzLSiZfCAYUGXgT0CdbBS0hiWM3NG2PzRPuor4D50Dy7qPi1PFTfFrBMK9WY/yVbfd4PoTQ/iJNlnn+yJ1e/BeHfXhKusnOo5Nu8F8+B7MdFq5LYbxu8XmtW232Jq99qzptSr8BIzXk4XFe1dhFH7aoW4by3OgCI3ioF9Za9IHOUudGbaIesh55gYdxhbQfYv9vtDibkSuDrRV9+9YFLXiXJSbYQ6iYWSOwzUlJS9xao4xu/IJDlCgMtoW4ZtkU4mB9PRAzO2LHqOoBl1tQ9UjUnAgu0k6i/xppvL5bcHdU="
